# Generated by Django 2.1 on 2019-03-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Doc_File',
            new_name='Doc_File_Path',
        ),
    ]
