# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20190306_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Duration',
            field=models.CharField(default=30, max_length=10),
            preserve_default=False,
        ),
    ]
