# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20190315_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Doc_File_Path',
            field=models.FileField(upload_to='video/'),
        ),
    ]
